### DataFrame 조회(read)
- 컬럼명
- loc, iloc
- indexing과 활용

**컬럼명**을 사용하여 원하는 컬럼만 뽑아낼 수 있다.

df[컬럼명]

In [2]:
import pandas as pd

In [13]:
sample = pd.read_csv("./내국인 생활인구.csv", encoding="cp949")
sample = sample.set_index("일자(stdr_de_id)")
sample.head()

,시간(tmzon_pd_se),행정동코드(adstrd_code_se),집계구코드(oa_cd),생활인구합계(tot_lvpop_co),남자0~9세(male_f0t9_lvpop_co),남자10~14세(male_f10t14_lvpop_co),남자15~19세(male_f15t19_lvpop_co),남자20~24세(male_f20t24_lvpop_co),남자25~29세(male_f25t29_lvpop_co),남자30~34세(male_f30t34_lvpop_co),...,여자40~44세(female_f40t44_lvpop_co),여자45~49세(female_f45t49_lvpop_co),여자50~54세(female_f50t54_lvpop_co),여자55~59세(female_f55t59_lvpop_co),여자60~64세(female_f60t64_lvpop_co),여자65~69세(female_f65t69_lvpop_co),여자70~74세(female_f70t74_lvpop_co),여자75~79세(female_f75t79_lvpop_co),여자80세이상(female_above_80_lvpop_co),등록일자(ldadng_dt)
일자(stdr_de_id),,,,,,,,,,,,,,,,,,,,,
20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,13.4910,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,8.4651,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,1.2299,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,27.6958,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,115.6026,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44

컬럼명 가공하기

일자(str_de_id) -> 일자

이런식으로 가공

In [14]:
#split 함수를 사용

"안녕(hello)".split("(")

['안녕', 'hello)']

In [15]:
newCols = []
cols = sample.columns

for col in cols:
    newCols.append(col.split("(")[0])

newCols

['시간',
 '행정동코드',
 '집계구코드',
 '생활인구합계',
 '남자0~9세',
 '남자10~14세',
 '남자15~19세',
 '남자20~24세',
 '남자25~29세',
 '남자30~34세',
 '남자35~39세',
 '남자40~44세',
 '남자45~49세',
 '남자50~54세',
 '남자55~59세',
 '남자60~64세',
 '남자65~69세',
 '남자70~74세',
 '남자75~79세',
 '남자80세이상',
 '여자0~9세',
 '여자10~14세',
 '여자15~19세',
 '여자20~24세',
 '여자25~29세',
 '여자30~34세',
 '여자35~39세',
 '여자40~44세',
 '여자45~49세',
 '여자50~54세',
 '여자55~59세',
 '여자60~64세',
 '여자65~69세',
 '여자70~74세',
 '여자75~79세',
 '여자80세이상',
 '등록일자']

In [16]:
sample.columns = newCols
sample.head()

,시간,행정동코드,집계구코드,생활인구합계,남자0~9세,남자10~14세,남자15~19세,남자20~24세,남자25~29세,남자30~34세,...,여자40~44세,여자45~49세,여자50~54세,여자55~59세,여자60~64세,여자65~69세,여자70~74세,여자75~79세,여자80세이상,등록일자
일자(stdr_de_id),,,,,,,,,,,,,,,,,,,,,
20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,13.4910,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,8.4651,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,1.2299,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,27.6958,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,115.6026,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44

1개의 컬럼 조회

In [17]:
sample["시간"]

일자(stdr_de_id)
20170226     4
20180107    22
20180317     6
20190222     7
20210706     6
            ..
20170603     7
20211007     5
20200819    20
20171011    11
20200725    21
Name: 시간, Length: 500, dtype: int64

In [18]:
sample[["시간", "남자10~14세"]]

                시간  남자10~14세
일자(stdr_de_id)
20170226         4    8.2257
20180107        22    3.1141
20180317         6  324.3596
20190222         7   14.3256
20210706         6    2.9824
...             ..       ...
20170603         7    4.2056
20211007         5    8.1278
20200819        20   14.3413
20171011        11    8.4071
20200725        21   12.6652

[500 rows x 2 columns]

#### loc, iloc 함수
두 함수를 사용하여 원하는 행 또는 열에 인덱싱, 슬라이싱이 가능하다
- loc[행인덱스] -> row 조회
- loc[행인덱스, 컬럼명] -> row & column 조회

- iloc[행인덱스번호] -> row 조회
- iloc[행인덱스번호, 열인덱스번호] -> row & column 조회

In [19]:
sample.head()

,시간,행정동코드,집계구코드,생활인구합계,남자0~9세,남자10~14세,남자15~19세,남자20~24세,남자25~29세,남자30~34세,...,여자40~44세,여자45~49세,여자50~54세,여자55~59세,여자60~64세,여자65~69세,여자70~74세,여자75~79세,여자80세이상,등록일자
일자(stdr_de_id),,,,,,,,,,,,,,,,,,,,,
20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,13.4910,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,8.4651,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,1.2299,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,27.6958,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,115.6026,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44

loc[행인덱스] -> row조회

In [20]:
sample.loc[20170226]

시간                            4
행정동코드                  11320515
집계구코드             1125061020007
생활인구합계                   4.3097
남자0~9세                  11.9781
남자10~14세                 8.2257
남자15~19세                 1.8759
남자20~24세                 4.2075
남자25~29세                 6.2647
남자30~34세                 13.491
남자35~39세                13.5164
남자40~44세                19.3318
남자45~49세                 3.2175
남자50~54세                 13.066
남자55~59세                 0.7311
남자60~64세                10.3675
남자65~69세                54.4338
남자70~74세                10.7428
남자75~79세                12.6761
남자80세이상                 18.0326
여자0~9세                   7.0317
여자10~14세                 5.5756
여자15~19세                    0.0
여자20~24세                69.8919
여자25~29세                 3.1963
여자30~34세                 4.7035
여자35~39세                26.6858
여자40~44세                 9.0816
여자45~49세                52.6711
여자50~54세                24.9152
여자55~59세                 3.6202
여자60~64세                91.3448
여자65~69세                13.6818
여자70~74세                 45.288
여자75~79세                 2.3141
여자80세이상                  9.7668
등록일자        2021-08-17 16:06:44
Name: 20170226, dtype: object

In [21]:
sample.loc[20170226:20180317]

,시간,행정동코드,집계구코드,생활인구합계,남자0~9세,남자10~14세,남자15~19세,남자20~24세,남자25~29세,남자30~34세,...,여자40~44세,여자45~49세,여자50~54세,여자55~59세,여자60~64세,여자65~69세,여자70~74세,여자75~79세,여자80세이상,등록일자
일자(stdr_de_id),,,,,,,,,,,,,,,,,,,,,
20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,13.4910,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,8.4651,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,1.2299,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44

loc[행인덱스, 컬럼명] -> row&column 조회

In [22]:
sample.loc[:, ["시간", "집계구코드"]]

                시간          집계구코드
일자(stdr_de_id)
20170226         4  1125061020007
20180107        22  1115071010309
20180317         6  1113073020101
20190222         7  1106071020403
20210706         6  1107073040015
...             ..            ...
20170603         7  1122057010104
20211007         5  1111056061002
20200819        20  1121078010101
20171011        11  1121082010004
20200725        21  1115053030001

[500 rows x 2 columns]

iloc[행인덱스번호] -> row 조회

In [24]:
sample.iloc[0:3]

,시간,행정동코드,집계구코드,생활인구합계,남자0~9세,남자10~14세,남자15~19세,남자20~24세,남자25~29세,남자30~34세,...,여자40~44세,여자45~49세,여자50~54세,여자55~59세,여자60~64세,여자65~69세,여자70~74세,여자75~79세,여자80세이상,등록일자
일자(stdr_de_id),,,,,,,,,,,,,,,,,,,,,
20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,13.4910,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,8.4651,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,1.2299,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44

In [25]:
sample.iloc[:, 0:3]

                시간     행정동코드          집계구코드
일자(stdr_de_id)
20170226         4  11320515  1125061020007
20180107        22  11380510  1115071010309
20180317         6  11680610  1113073020101
20190222         7  11305575  1106071020403
20210706         6  11740660  1107073040015
...             ..       ...            ...
20170603         7  11650560  1122057010104
20211007         5  11620525  1111056061002
20200819        20  11140635  1121078010101
20171011        11  11590605  1121082010004
20200725        21  11350625  1115053030001

[500 rows x 3 columns]

#### indexing과 활용

조건에 따라 원하는 부분만 가져오고 싶은 경우가 있다. 이런 것을 인덱싱이라고 함

In [26]:
sample.head()

,시간,행정동코드,집계구코드,생활인구합계,남자0~9세,남자10~14세,남자15~19세,남자20~24세,남자25~29세,남자30~34세,...,여자40~44세,여자45~49세,여자50~54세,여자55~59세,여자60~64세,여자65~69세,여자70~74세,여자75~79세,여자80세이상,등록일자
일자(stdr_de_id),,,,,,,,,,,,,,,,,,,,,
20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,13.4910,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,8.4651,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,1.2299,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,27.6958,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,115.6026,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44

생활 인구 합계가 1000 이상인 데이터만 가져오고 싶다면?

In [27]:
sample["생활인구합계"] >= 1000

일자(stdr_de_id)
20170226    False
20180107    False
20180317     True
20190222    False
20210706    False
            ...
20170603    False
20211007    False
20200819    False
20171011    False
20200725     True
Name: 생활인구합계, Length: 500, dtype: bool

In [28]:
sample[sample["생활인구합계"] >= 1000]

,시간,행정동코드,집계구코드,생활인구합계,남자0~9세,남자10~14세,남자15~19세,남자20~24세,남자25~29세,남자30~34세,...,여자40~44세,여자45~49세,여자50~54세,여자55~59세,여자60~64세,여자65~69세,여자70~74세,여자75~79세,여자80세이상,등록일자
일자(stdr_de_id),,,,,,,,,,,,,,,,,,,,,
20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,1.2299,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
20170408,8,11740685,1119066010105,1079.7134,4.0917,10.8796,12.4219,1.6562,21.9264,60.8998,...,10.8313,23.4527,4.1431,22.1996,26.9575,8.3431,14.4447,48.9427,0.0104,2021-08-17 16:06:44
20200614,1,11260655,1125067010020,1036.2064,40.3825,1.7486,39.8508,29.1526,4.6644,4.8052,...,22.9719,12.4215,73.2060,4.0706,20.4086,14.1957,12.4370,4.9715,4.1581,2021-08-17 16:06:44
20201222,22,11350611,1111078010103,1364.5008,14.9106,4.2902,0.0000,9.8438,111.6884,91.9557,...,28.9179,0.1007,2.4184,26.5816,6.5845,1.4204,7.7075,0.0000,6.3707,2021-08-17 16:06:44
20190721,7,11530730,1106090030013,2327.7078,17.3709,0.0001,30.8019,0.8422,15.7040,2.2680,...,69.5434,6.9826,0.0000,24.8227,16.4284,9.6311,2.4498,6.1293,135.2059,2021-08-17 16:06:44
20210909,8,11710531,1124082020501,1386.5192,4.4293,2.9420,39.6386,49.4549,16.6462,3.1906,...,52.5776,102.9158,2.5967,19.8164,1.0700,21.9317,17.1770,5.4685,15.1598,2021-08-17 16:06:44
20180726,13,11290760,1107052020003,1434.0143,2.0398,15.1825,19.4212,5.1919,4.8996,4.6031,...,1.3943,16.0489,25.3726,8.4143,6.3157,8.2121,11.9664,9.9346,11.2276,2021-08-17 16:06:44
20170531,0,11620585,1122057020020,1990.2866,4.4616,18.0789,26.7599,2.9089,3.2441,51.5304,...,28.5016,15.4471,15.8105,20.5129,16.7786,65.6481,0.1607,10.8671,5.1480,2021-08-17 16:06:44
20210125,18,11230660,1117071050004,1236.1459,16.4584,8.1088,8.0762,33.7676,21.3094,14.7762,...,1.1522,37.2469,6.6728,37.6457,34.6523,0.0000,5.7561,8.9008,2.4971,2021-08-17 16:06:44
20180210,21,11320522,1110053010203,1371.0830,1.9326,4.3819,10.1386,4.4866,3.0363,23.7286,...,0.0000,27.6105,3.3312,5.6744,6.4734,1.6007,12.2914,3.0483,3.0373,2021-08-17 16:06:44
20180911,11,11230750,1116054020404,1406.6014,0.8223,12.5166,11.0455,10.1962,87.5671,20.3759,...,33.6715,4.1725,58.4382,8.7975,1.1424,12.7861,2.9762,32.7337,8.3680,2021-08-17 16:06:44
20191001,20,11350560,1108072040101,1783.4770,48.6429,6.4575,21.1578,0.0000,12.9875,48.0078,...,31.6392,36.2287,10.1524,45.0366,24.4490,7.0886,14.6355,13.2220,7.8829,2021-08-17 16:06:44
20180118,22,11260620,1109071020012,1565.8248,8.9839,52.6619,10.9559,2.5538,0.0013,10.1352,...,22.4793,0.8152,8.0029,1.1364,5.4317,19.0242,14.2020,0.5337,6.0197,2021-08-17 16:06:44
20200411,14,11740570,1110064050012,1366.7424,10.8791,7.4792,0.8134,16.7097,37.4600,14.6182,...,0.1879,5.8184,40.6834,15.2324,4.1339,19.7984,14.1861,2.7476,29.4760,2021-08-17 16:06:44
20210211,2,11620745,1124064020006,1655.3044,11.8173,1.2880,0.1472,7.8770,5.9064,6.1888,...,6.0575,4.9062,37.8242,5.2411,38.5508,0.8612,11.6205,0.3226,10.3449,2021-08-17 16:06:44
20200329,6,11380560,1106082040001,2228.7185,8.8008,7.0174,5.6227,1.1800,13.0293,29.5969,...,3.8377,10.1295,8.9036,9.7149,0.0201,8.5640,4.6981,9.4865,21.9198,2021-08-17 16:06:44
20190415,21,11230536,1112071030212,2085.4572,3.3884,0.0000,11.7617,3.1087,3.6294,2.9016,...,4.9100,48.8234,20.9956,19.1820,9.0738,11.5902,20.7307,2.8346,8.0001,2021-08-17 16:06:44
20190327,11,11230560,1117056020007,1398.3094,11.2592,25.1832,19.1054,5.7555,51.1001,9.0165,...,16.3633,5.9035,9.1557,29.7711,7.1099,11.3225,2.2679,5.3521,0.0000,2021-08-17 16:06:44
20180605,1,11650651,1116065010201,1386.7631,19.2866,7.2028,11.4853,21.1352,0.1403,6.2833,...,49.3682,20.2083,6.4640,25.0187,31.4656,23.8641,0.8673,7.5028,0.0000,2021-08-17 16:06:44
20180610,21,11200660,1124056020009,1186.4004,36.7111,2.3799,13.3270,9.9946,30.7940,9.4902,...,23.0685,29.4002,4.5916,32.2697,1.6506,7.0680,2.7828,5.7200,10.4302,2021-08-17 16:06:44
20181228,11,11230545,1121080010027,5177.5209,0.0385,5.3920,8.0849,0.2271,13.5296,1.1309,...,0.0000,0.9412,8.8398,1.0344,20.9504,30.7662,1.8254,3.4691,4.1213,2021-08-17 16:06:44
20200112,0,11305534,1116074030404,1160.3397,18.8974,1.3862,15.5971,22.7036,15.8658,2.0374,...,18.2624,20.0088,6.5824,58.3617,4.2726,15.9158,11.4753,6.5915,43.3072,2021-08-17 16:06:44
20171022,10,11620585,1111065031302,1058.9857,19.6579,5.3807,15.8241,62.1404,2.8271,7.0195,...,17.3769,2.7599,4.3683,14.5347,49.3751,1.0272,35.8797,3.0176,10.2636,2021-08-17 16:06:44
20170901,15,11680565,1125074030002,1336.8165,5.1974,3.9016,4.5309,0.3567,34.6220,14.1477,...,22.2622,0.2274,4.5297,36.5760,42.1549,0.0000,0.7729,5.0544,7.1974,2021-08-17 16:06:44
20210912,18,11680610,1101067020003,1256.1622,14.6004,2.7720,42.3772,17.0723,0.0000,1.8279,...,14.0487,15.6679,8.4220,3.0203,14.0333,6.2122,17.1422,5.2644,0.7601,2021-08-17 16:06:44
20210810,6,11560605,1120055030002,2520.1710,4.0091,18.2295,20.3945,6.5419,0.5712,4.1387,...,0.0000,29.5524,0.0433,29.1001,2.8215,4.4647,4.2977,4.1053,11.5568,2021-08-17 16:06:44
20180116,20,11545610,1125071020023,1129.0995,18.8777,12.8585,1.2552,11.4815,21.8688,6.0641,...,48.8743,14.6528,9.4839,6.5791,12.5301,7.0475,5.4371,22.8315,11.0942,2021-08-17 16:06:44
20200103,2,11620625,1121062010003,2090.4511,4.1527,50.2878,0.0000,8.5573,9.4212,38.1695,...,2.7634,30.0812,25.0164,3.3767,11.0947,1.7491,0.1257,0.1179,7.6388,2021-08-17 16:06:44
20180311,15,11305545,1121057030005,6227.8554,15.4750,1.8353,5.1934,11.0780,28.9441,0.8222,...,6.2275,12.9162,3.3052,4.8125,21.8676,59.6745,1.9171,4.0661,15.1511,2021-08-17 16:06:44
20191101,13,11740620,1104072010009,1720.8376,9.2131,4.2412,70.0325,4.0475,2.3249,33.6956,...,26.7227,44.6527,32.2059,44.1358,0.0001,7.0940,11.0619,0.0000,29.1684,2021-08-17 16:06:44
20170817,22,11740540,1113064020201,1635.2666,3.2201,8.6190,4.3749,15.9845,0.2012,4.9270,...,72.2597,3.1570,7.9399,82.2985,15.7115,4.1594,1.6518,17.4340,7.1715,2021-08-17 16:06:44
20180110,1,11230560,1107052010006,1778.9074,0.0000,15.5303,24.5134,2.5042,15.4098,11.3305,...,20.4836,16.6887,0.0000,30.1587,5.7483,5.7807,6.6494,0.4378,4.1866,2021-08-17 16:06:44
20210713,6,11305534,1122061020001,2057.7860,32.0560,5.5098,13.9872,5.2714,17.6793,21.9106,...,3.4689,41.0688,4.8768,7.8001,17.0770,7.1459,9.2279,11.3788,15.0431,2021-08-17 16:06:44
20201001,3,11380640,1121057010002,1436.8979,21.2596,6.0768,0.8027,13.5965,5.3034,0.6251,...,7.4061,0.4501,17.8329,50.2653,88.0399,1.9082,6.3093,0.5917,15.2854,2021-08-17 16:06:44
20210715,22,11680610,1125067010014,2556.0814,7.6816,11.3859,10.7294,22.2396,7.6053,40.2110,...,7.2711,11.9893,1.8917,20.5252,21.7313,39.0403,0.8007,18.6659,64.2800,2021-08-17 16:06:44
20180919,18,11590660,1116074040113,3881.1727,4.3330,8.0110,28.8220,11.4180,17.2960,6.7327,...,8.8032,13.4178,20.7619,3.4012,11.5815,12.3637,17.5769,0.9599,5.3240,2021-08-17 16:06:44
20171002,16,11530530,1117068032002,1282.2526,23.0828,14.0663,9.8191,3.8079,10.5723,20.8415,...,12.5622,18.4479,6.6117,1.6994,6.0687,18.9183,37.6874,26.7823,4.1775,2021-08-17 16:06:44
20190303,12,11215710,1111074050109,1036.6069,5.4409,4.4767,25.0834,6.7721,45.8473,2.5469,...,12.6749,13.7502,11.0601,17.6551,14.0544,209.2460,0.5207,25.7174,0.0134,2021-08-17 16:06:44
20191114,1,11590660,1110056020010,1271.6886,11.9871,5.6790,0.0933,22.4880,3.1414,19.9542,...,20.8399,33.7336,1.1004,17.6112,0.1005,6.9641,9.1556,15.4356,4.0028,2021-08-17 16:06:44
20200228,14,11320710,1109063010006,1058.4189,9.1089,17.5415,6.3995,21.6999,5.3959,41.0039,...,5.1175,22.2493,28.8520,2.4714,0.0000,2.1065,8.0656,1.2578,5.9254,2021-08-17 16:06:44
20170126,4,11410640,1103073020601,1019.1132,45.1427,3.2134,3.1155,19.4055,8.7534,0.2782,...,0.3558,31.4430,46.1798,2.9051,33.6343,13.3721,50.0566,4.6074,33.1837,2021-08-17 16:06:44
20181219,14,11710620,1124069010121,3032.0255,0.4255,15.2956,9.2320,31.6295,11.7810,6.7418,...,4.5043,22.7120,19.4895,22.1769,19.4117,0.2766,4.5259,9.1296,7.2543,2021-08-17 16:06:44
20180502,15,11680565,1101069010104,1455.1261,0.4946,7.9006,3.5089,4.3957,21.3624,5.9364,...,3.7152,7.1566,12.6903,56.8525,0.1517,67.9536,0.9452,27.5280,0.0355,2021-08-17 16:06:44
20200626,3,11230536,1112059030302,6759.4381,2.4282,5.9047,0.4558,42.4836,19.4623,28.9189,...,14.8910,6.8444,0.0000,1.6781,16.7879,35.1239,8.4813,4.1938,83.6384,2021-08-17 16:06:44
20180531,4,11350630,1118060010004,1027.8019,27.1971,7.3991,21.0711,12.2825,4.4542,3.6381,...,15.7845,9.3562,15.0851,62.9548,4.1010,3.8431,74.8304,36.8624,5.5826,2021-08-17 16:06:44
20201028,18,11410685,1116073020015,1442.9434,22.7521,9.2947,9.5528,22.3573,28.5781,12.3402,...,49.5311,19.6706,8.1495,277.8552,158.2342,10.0129,3.0016,5.4136,10.0308,2021-08-17 16:06:44
20180522,5,11380551,1107073010003,1087.2762,0.0000,0.2330,4.9595,8.4416,15.5648,6.1428,...,11.2837,10.1499,31.0671,364.2145,6.2032,7.8198,15.5331,0.6995,2.0185,2021-08-17 16:06:44
20190426,21,11410565,1112065020302,1046.8655,7.8923,2.9935,24.9856,22.1082,65.1641,21.9532,...,4.4642,18.8361,25.2945,53.2859,2.6267,9.5995,9.3026,2.1655,8.8593,2021-08-17 16:06:44
20200725,21,11350625,1115053030001,1098.0798,12.6300,12.6652,18.6522,275.4479,20.0665,35.7657,...,63.2687,18.9043,36.0630,27.1679,18.4721,13.1369,21.8967,6.0132,4.8362,2021-08-17 16:06:44

In [29]:
sample.loc[sample["생활인구합계"] >= 1000]

,시간,행정동코드,집계구코드,생활인구합계,남자0~9세,남자10~14세,남자15~19세,남자20~24세,남자25~29세,남자30~34세,...,여자40~44세,여자45~49세,여자50~54세,여자55~59세,여자60~64세,여자65~69세,여자70~74세,여자75~79세,여자80세이상,등록일자
일자(stdr_de_id),,,,,,,,,,,,,,,,,,,,,
20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,1.2299,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
20170408,8,11740685,1119066010105,1079.7134,4.0917,10.8796,12.4219,1.6562,21.9264,60.8998,...,10.8313,23.4527,4.1431,22.1996,26.9575,8.3431,14.4447,48.9427,0.0104,2021-08-17 16:06:44
20200614,1,11260655,1125067010020,1036.2064,40.3825,1.7486,39.8508,29.1526,4.6644,4.8052,...,22.9719,12.4215,73.2060,4.0706,20.4086,14.1957,12.4370,4.9715,4.1581,2021-08-17 16:06:44
20201222,22,11350611,1111078010103,1364.5008,14.9106,4.2902,0.0000,9.8438,111.6884,91.9557,...,28.9179,0.1007,2.4184,26.5816,6.5845,1.4204,7.7075,0.0000,6.3707,2021-08-17 16:06:44
20190721,7,11530730,1106090030013,2327.7078,17.3709,0.0001,30.8019,0.8422,15.7040,2.2680,...,69.5434,6.9826,0.0000,24.8227,16.4284,9.6311,2.4498,6.1293,135.2059,2021-08-17 16:06:44
20210909,8,11710531,1124082020501,1386.5192,4.4293,2.9420,39.6386,49.4549,16.6462,3.1906,...,52.5776,102.9158,2.5967,19.8164,1.0700,21.9317,17.1770,5.4685,15.1598,2021-08-17 16:06:44
20180726,13,11290760,1107052020003,1434.0143,2.0398,15.1825,19.4212,5.1919,4.8996,4.6031,...,1.3943,16.0489,25.3726,8.4143,6.3157,8.2121,11.9664,9.9346,11.2276,2021-08-17 16:06:44
20170531,0,11620585,1122057020020,1990.2866,4.4616,18.0789,26.7599,2.9089,3.2441,51.5304,...,28.5016,15.4471,15.8105,20.5129,16.7786,65.6481,0.1607,10.8671,5.1480,2021-08-17 16:06:44
20210125,18,11230660,1117071050004,1236.1459,16.4584,8.1088,8.0762,33.7676,21.3094,14.7762,...,1.1522,37.2469,6.6728,37.6457,34.6523,0.0000,5.7561,8.9008,2.4971,2021-08-17 16:06:44
20180210,21,11320522,1110053010203,1371.0830,1.9326,4.3819,10.1386,4.4866,3.0363,23.7286,...,0.0000,27.6105,3.3312,5.6744,6.4734,1.6007,12.2914,3.0483,3.0373,2021-08-17 16:06:44
20180911,11,11230750,1116054020404,1406.6014,0.8223,12.5166,11.0455,10.1962,87.5671,20.3759,...,33.6715,4.1725,58.4382,8.7975,1.1424,12.7861,2.9762,32.7337,8.3680,2021-08-17 16:06:44
20191001,20,11350560,1108072040101,1783.4770,48.6429,6.4575,21.1578,0.0000,12.9875,48.0078,...,31.6392,36.2287,10.1524,45.0366,24.4490,7.0886,14.6355,13.2220,7.8829,2021-08-17 16:06:44
20180118,22,11260620,1109071020012,1565.8248,8.9839,52.6619,10.9559,2.5538,0.0013,10.1352,...,22.4793,0.8152,8.0029,1.1364,5.4317,19.0242,14.2020,0.5337,6.0197,2021-08-17 16:06:44
20200411,14,11740570,1110064050012,1366.7424,10.8791,7.4792,0.8134,16.7097,37.4600,14.6182,...,0.1879,5.8184,40.6834,15.2324,4.1339,19.7984,14.1861,2.7476,29.4760,2021-08-17 16:06:44
20210211,2,11620745,1124064020006,1655.3044,11.8173,1.2880,0.1472,7.8770,5.9064,6.1888,...,6.0575,4.9062,37.8242,5.2411,38.5508,0.8612,11.6205,0.3226,10.3449,2021-08-17 16:06:44
20200329,6,11380560,1106082040001,2228.7185,8.8008,7.0174,5.6227,1.1800,13.0293,29.5969,...,3.8377,10.1295,8.9036,9.7149,0.0201,8.5640,4.6981,9.4865,21.9198,2021-08-17 16:06:44
20190415,21,11230536,1112071030212,2085.4572,3.3884,0.0000,11.7617,3.1087,3.6294,2.9016,...,4.9100,48.8234,20.9956,19.1820,9.0738,11.5902,20.7307,2.8346,8.0001,2021-08-17 16:06:44
20190327,11,11230560,1117056020007,1398.3094,11.2592,25.1832,19.1054,5.7555,51.1001,9.0165,...,16.3633,5.9035,9.1557,29.7711,7.1099,11.3225,2.2679,5.3521,0.0000,2021-08-17 16:06:44
20180605,1,11650651,1116065010201,1386.7631,19.2866,7.2028,11.4853,21.1352,0.1403,6.2833,...,49.3682,20.2083,6.4640,25.0187,31.4656,23.8641,0.8673,7.5028,0.0000,2021-08-17 16:06:44
20180610,21,11200660,1124056020009,1186.4004,36.7111,2.3799,13.3270,9.9946,30.7940,9.4902,...,23.0685,29.4002,4.5916,32.2697,1.6506,7.0680,2.7828,5.7200,10.4302,2021-08-17 16:06:44
20181228,11,11230545,1121080010027,5177.5209,0.0385,5.3920,8.0849,0.2271,13.5296,1.1309,...,0.0000,0.9412,8.8398,1.0344,20.9504,30.7662,1.8254,3.4691,4.1213,2021-08-17 16:06:44
20200112,0,11305534,1116074030404,1160.3397,18.8974,1.3862,15.5971,22.7036,15.8658,2.0374,...,18.2624,20.0088,6.5824,58.3617,4.2726,15.9158,11.4753,6.5915,43.3072,2021-08-17 16:06:44
20171022,10,11620585,1111065031302,1058.9857,19.6579,5.3807,15.8241,62.1404,2.8271,7.0195,...,17.3769,2.7599,4.3683,14.5347,49.3751,1.0272,35.8797,3.0176,10.2636,2021-08-17 16:06:44
20170901,15,11680565,1125074030002,1336.8165,5.1974,3.9016,4.5309,0.3567,34.6220,14.1477,...,22.2622,0.2274,4.5297,36.5760,42.1549,0.0000,0.7729,5.0544,7.1974,2021-08-17 16:06:44
20210912,18,11680610,1101067020003,1256.1622,14.6004,2.7720,42.3772,17.0723,0.0000,1.8279,...,14.0487,15.6679,8.4220,3.0203,14.0333,6.2122,17.1422,5.2644,0.7601,2021-08-17 16:06:44
20210810,6,11560605,1120055030002,2520.1710,4.0091,18.2295,20.3945,6.5419,0.5712,4.1387,...,0.0000,29.5524,0.0433,29.1001,2.8215,4.4647,4.2977,4.1053,11.5568,2021-08-17 16:06:44
20180116,20,11545610,1125071020023,1129.0995,18.8777,12.8585,1.2552,11.4815,21.8688,6.0641,...,48.8743,14.6528,9.4839,6.5791,12.5301,7.0475,5.4371,22.8315,11.0942,2021-08-17 16:06:44
20200103,2,11620625,1121062010003,2090.4511,4.1527,50.2878,0.0000,8.5573,9.4212,38.1695,...,2.7634,30.0812,25.0164,3.3767,11.0947,1.7491,0.1257,0.1179,7.6388,2021-08-17 16:06:44
20180311,15,11305545,1121057030005,6227.8554,15.4750,1.8353,5.1934,11.0780,28.9441,0.8222,...,6.2275,12.9162,3.3052,4.8125,21.8676,59.6745,1.9171,4.0661,15.1511,2021-08-17 16:06:44
20191101,13,11740620,1104072010009,1720.8376,9.2131,4.2412,70.0325,4.0475,2.3249,33.6956,...,26.7227,44.6527,32.2059,44.1358,0.0001,7.0940,11.0619,0.0000,29.1684,2021-08-17 16:06:44
20170817,22,11740540,1113064020201,1635.2666,3.2201,8.6190,4.3749,15.9845,0.2012,4.9270,...,72.2597,3.1570,7.9399,82.2985,15.7115,4.1594,1.6518,17.4340,7.1715,2021-08-17 16:06:44
20180110,1,11230560,1107052010006,1778.9074,0.0000,15.5303,24.5134,2.5042,15.4098,11.3305,...,20.4836,16.6887,0.0000,30.1587,5.7483,5.7807,6.6494,0.4378,4.1866,2021-08-17 16:06:44
20210713,6,11305534,1122061020001,2057.7860,32.0560,5.5098,13.9872,5.2714,17.6793,21.9106,...,3.4689,41.0688,4.8768,7.8001,17.0770,7.1459,9.2279,11.3788,15.0431,2021-08-17 16:06:44
20201001,3,11380640,1121057010002,1436.8979,21.2596,6.0768,0.8027,13.5965,5.3034,0.6251,...,7.4061,0.4501,17.8329,50.2653,88.0399,1.9082,6.3093,0.5917,15.2854,2021-08-17 16:06:44
20210715,22,11680610,1125067010014,2556.0814,7.6816,11.3859,10.7294,22.2396,7.6053,40.2110,...,7.2711,11.9893,1.8917,20.5252,21.7313,39.0403,0.8007,18.6659,64.2800,2021-08-17 16:06:44
20180919,18,11590660,1116074040113,3881.1727,4.3330,8.0110,28.8220,11.4180,17.2960,6.7327,...,8.8032,13.4178,20.7619,3.4012,11.5815,12.3637,17.5769,0.9599,5.3240,2021-08-17 16:06:44
20171002,16,11530530,1117068032002,1282.2526,23.0828,14.0663,9.8191,3.8079,10.5723,20.8415,...,12.5622,18.4479,6.6117,1.6994,6.0687,18.9183,37.6874,26.7823,4.1775,2021-08-17 16:06:44
20190303,12,11215710,1111074050109,1036.6069,5.4409,4.4767,25.0834,6.7721,45.8473,2.5469,...,12.6749,13.7502,11.0601,17.6551,14.0544,209.2460,0.5207,25.7174,0.0134,2021-08-17 16:06:44
20191114,1,11590660,1110056020010,1271.6886,11.9871,5.6790,0.0933,22.4880,3.1414,19.9542,...,20.8399,33.7336,1.1004,17.6112,0.1005,6.9641,9.1556,15.4356,4.0028,2021-08-17 16:06:44
20200228,14,11320710,1109063010006,1058.4189,9.1089,17.5415,6.3995,21.6999,5.3959,41.0039,...,5.1175,22.2493,28.8520,2.4714,0.0000,2.1065,8.0656,1.2578,5.9254,2021-08-17 16:06:44
20170126,4,11410640,1103073020601,1019.1132,45.1427,3.2134,3.1155,19.4055,8.7534,0.2782,...,0.3558,31.4430,46.1798,2.9051,33.6343,13.3721,50.0566,4.6074,33.1837,2021-08-17 16:06:44
20181219,14,11710620,1124069010121,3032.0255,0.4255,15.2956,9.2320,31.6295,11.7810,6.7418,...,4.5043,22.7120,19.4895,22.1769,19.4117,0.2766,4.5259,9.1296,7.2543,2021-08-17 16:06:44
20180502,15,11680565,1101069010104,1455.1261,0.4946,7.9006,3.5089,4.3957,21.3624,5.9364,...,3.7152,7.1566,12.6903,56.8525,0.1517,67.9536,0.9452,27.5280,0.0355,2021-08-17 16:06:44
20200626,3,11230536,1112059030302,6759.4381,2.4282,5.9047,0.4558,42.4836,19.4623,28.9189,...,14.8910,6.8444,0.0000,1.6781,16.7879,35.1239,8.4813,4.1938,83.6384,2021-08-17 16:06:44
20180531,4,11350630,1118060010004,1027.8019,27.1971,7.3991,21.0711,12.2825,4.4542,3.6381,...,15.7845,9.3562,15.0851,62.9548,4.1010,3.8431,74.8304,36.8624,5.5826,2021-08-17 16:06:44
20201028,18,11410685,1116073020015,1442.9434,22.7521,9.2947,9.5528,22.3573,28.5781,12.3402,...,49.5311,19.6706,8.1495,277.8552,158.2342,10.0129,3.0016,5.4136,10.0308,2021-08-17 16:06:44
20180522,5,11380551,1107073010003,1087.2762,0.0000,0.2330,4.9595,8.4416,15.5648,6.1428,...,11.2837,10.1499,31.0671,364.2145,6.2032,7.8198,15.5331,0.6995,2.0185,2021-08-17 16:06:44
20190426,21,11410565,1112065020302,1046.8655,7.8923,2.9935,24.9856,22.1082,65.1641,21.9532,...,4.4642,18.8361,25.2945,53.2859,2.6267,9.5995,9.3026,2.1655,8.8593,2021-08-17 16:06:44
20200725,21,11350625,1115053030001,1098.0798,12.6300,12.6652,18.6522,275.4479,20.0665,35.7657,...,63.2687,18.9043,36.0630,27.1679,18.4721,13.1369,21.8967,6.0132,4.8362,2021-08-17 16:06:44

생활인구합계가 1000 이상이고, 행정동 코드가 11680610인 데이터만 뽑아내자 (and)

In [33]:
condition = (sample["생활인구합계"] >= 1000) & (sample["행정동코드"] == 11680610)
condition

일자(stdr_de_id)
20170226    False
20180107    False
20180317     True
20190222    False
20210706    False
            ...
20170603    False
20211007    False
20200819    False
20171011    False
20200725    False
Length: 500, dtype: bool

In [34]:
sample[condition]

,시간,행정동코드,집계구코드,생활인구합계,남자0~9세,남자10~14세,남자15~19세,남자20~24세,남자25~29세,남자30~34세,...,여자40~44세,여자45~49세,여자50~54세,여자55~59세,여자60~64세,여자65~69세,여자70~74세,여자75~79세,여자80세이상,등록일자
일자(stdr_de_id),,,,,,,,,,,,,,,,,,,,,
20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,1.2299,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
20210912,18,11680610,1101067020003,1256.1622,14.6004,2.7720,42.3772,17.0723,0.0000,1.8279,...,14.0487,15.6679,8.4220,3.0203,14.0333,6.2122,17.1422,5.2644,0.7601,2021-08-17 16:06:44
20210715,22,11680610,1125067010014,2556.0814,7.6816,11.3859,10.7294,22.2396,7.6053,40.2110,...,7.2711,11.9893,1.8917,20.5252,21.7313,39.0403,0.8007,18.6659,64.2800,2021-08-17 16:06:44