### Series & DataFrame

- 판다스는 엑셀의 파이썬 버전
- 엑셀은 표(table)형태로 데이터를 저장
- 이 표가 바로 판다스에서는 DataFrame, DataFrame은 Series를 여러 개 붙여서 만들어짐

In [1]:
import pandas as pd

In [3]:
nums = [i for i in range(1,11)]
nums

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
seriesNums = pd.Series(nums)
seriesNums

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

### 애꿎은 list를 Series로 만드는 이유

- pandas의 다양한 기능을 사용하기 위해서

In [5]:
seriesNums.mean()

np.float64(5.5)

In [6]:
seriesNums.describe()

count    10.00000
mean      5.50000
std       3.02765
min       1.00000
25%       3.25000
50%       5.50000
75%       7.75000
max      10.00000
dtype: float64

### DataFrame을 생성하는 방법

In [7]:
nums = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [8]:
dfNums = pd.DataFrame(nums)
dfNums

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

### Series와 DataFrame 관계

- 여러개의 시리즈를 합친게 바로 데이터프레임

In [9]:
type(dfNums)

pandas.core.frame.DataFrame

In [10]:
dfNums[0]

0    1
1    4
2    7
Name: 0, dtype: int64

In [11]:
type(dfNums[0])

pandas.core.series.Series

### DataFrame을 생성하는 다른 방법
- 리스트 전달(위에서 했던 방식)

In [13]:
users = [
    ["철수", 180, 5],
    ["민수", 170, 5],
    ["짱구", 130, 5]
]

users

[['철수', 180, 5], ['민수', 170, 5], ['짱구', 130, 5]]

In [14]:
dfUsers = pd.DataFrame(users)
dfUsers

    0    1  2
0  철수  180  5
1  민수  170  5
2  짱구  130  5

- 컬럼 이름 설정하기

In [15]:
dfUsers.columns = ["name", "height", "age"]
dfUsers

  name  height  age
0   철수     180    5
1   민수     170    5
2   짱구     130    5

- 딕셔너리 전달

In [16]:
users = {
    "name": ["철수", "민수", "짱구"],
    "height": [180, 170, 130],
    "age": [25, 30, 5]
}
users

{'name': ['철수', '민수', '짱구'], 'height': [180, 170, 130], 'age': [25, 30, 5]}

In [17]:
dfUsers = pd.DataFrame(users)
dfUsers

  name  height  age
0   철수     180   25
1   민수     170   30
2   짱구     130    5

- 리스트 in 딕셔너리 전달

실제 현업에서는 api 요청의 결과로 이런 형식의 데이터 포맷으로 올 가능성이 크다

In [18]:
users = [
    {"name": "철수", "height": 180, "age": 25},
    {"name": "민수", "height": 170, "age": 30},
    {"name": "짱구", "height": 130, "age": 5},
]

users

[{'name': '철수', 'height': 180, 'age': 25},
 {'name': '민수', 'height': 170, 'age': 30},
 {'name': '짱구', 'height': 130, 'age': 5}]

In [19]:
dfUsers = pd.DataFrame(users)
dfUsers

  name  height  age
0   철수     180   25
1   민수     170   30
2   짱구     130    5

### DataFrame의 행, 열, 인덱스

In [20]:
sample = pd.read_csv("./내국인 생활인구.csv", encoding='cp949')

# 읽고자 하는 파일 내부에 한글이 있을 경우 잘 처리 함

In [21]:
sample

,일자(stdr_de_id),시간(tmzon_pd_se),행정동코드(adstrd_code_se),집계구코드(oa_cd),생활인구합계(tot_lvpop_co),남자0~9세(male_f0t9_lvpop_co),남자10~14세(male_f10t14_lvpop_co),남자15~19세(male_f15t19_lvpop_co),남자20~24세(male_f20t24_lvpop_co),남자25~29세(male_f25t29_lvpop_co),...,여자40~44세(female_f40t44_lvpop_co),여자45~49세(female_f45t49_lvpop_co),여자50~54세(female_f50t54_lvpop_co),여자55~59세(female_f55t59_lvpop_co),여자60~64세(female_f60t64_lvpop_co),여자65~69세(female_f65t69_lvpop_co),여자70~74세(female_f70t74_lvpop_co),여자75~79세(female_f75t79_lvpop_co),여자80세이상(female_above_80_lvpop_co),등록일자(ldadng_dt)
0,20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
1,20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
2,20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
3,20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
4,20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,20170603,7,11650560,1122057010104,465.8914,16.4274,4.2056,11.2869,3.5184,14.1803,...,17.2636,4.9406,16.3334,26.8672,1.0048,3.5458,18.9442,13.5570,17.3543,2021-08-17 16:06:44
496,20211007,5,11620525,1111056061002,180.1291,12.6887,8.1278,2.1684,23.3810,5.5894,...,9.7934,23.8109,10.2240,28.3686,9.9961,7.2371,5.7134,15.6473,6.1426,2021-08-17 16:06:44
497,20200819,20,11140635,1121078010101,540.8267,0.7004,14.3413,2.9791,0.2832,13.5837,...,0.0017,13.7260,14.1506,46.9632,10.5080,8.6825,3.9238,3.3179,13.5500,2021-08-17 16:06:44
498,20171011,11,11590605,1121082010004,992.2594,35.4771,8.4071,17.8773,1.2632,1.8164,...,3.9551,28.8403,10.7913,33.7729,1.4717,8.7947,8.5835,9.3403,0.0000,2021-08-17 16:06:44
499,20200725,21,11350625,1115053030001,1098.0798,12.6300,12.6652,18.6522,275.4479,20.0665,...,63.2687,18.9043,36.0630,27.1679,18.4721,13.1369,21.8967,6.0132,4.8362,2021-08-17 16:06:44

**head, tail 함수** 데이터가 너무 많으면 오히려 보기 불편할 수 있음

데이터 생김새만 보고 싶으면 맨 위 또는 맨 아래 n개만 볼 수 있는 기능

In [22]:
sample.head(6)

,일자(stdr_de_id),시간(tmzon_pd_se),행정동코드(adstrd_code_se),집계구코드(oa_cd),생활인구합계(tot_lvpop_co),남자0~9세(male_f0t9_lvpop_co),남자10~14세(male_f10t14_lvpop_co),남자15~19세(male_f15t19_lvpop_co),남자20~24세(male_f20t24_lvpop_co),남자25~29세(male_f25t29_lvpop_co),...,여자40~44세(female_f40t44_lvpop_co),여자45~49세(female_f45t49_lvpop_co),여자50~54세(female_f50t54_lvpop_co),여자55~59세(female_f55t59_lvpop_co),여자60~64세(female_f60t64_lvpop_co),여자65~69세(female_f65t69_lvpop_co),여자70~74세(female_f70t74_lvpop_co),여자75~79세(female_f75t79_lvpop_co),여자80세이상(female_above_80_lvpop_co),등록일자(ldadng_dt)
0,20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
1,20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
2,20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
3,20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
4,20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44
5,20170801,1,11530750,1123065020005,265.0386,4.6381,2.6234,15.7882,1.6462,23.5687,...,7.4000,10.4536,10.7581,2.3868,17.6019,1.1360,3.6187,4.5029,5.1927,2021-08-17 16:06:44

**index**

- 인덱스는 책의 목차같은 개념
- 더 빠르게 검색하고 데이터를 정렬할 때 사용되는 개념

In [23]:
sample.index

RangeIndex(start=0, stop=500, step=1)

기본 인덱스는 의미가 없음, 여기서는 일자 컬럼을 인덱스로 지정

In [27]:
sample = pd.read_csv("./내국인 생활인구.csv", encoding='cp949', index_col=0)
sample.head()

,시간(tmzon_pd_se),행정동코드(adstrd_code_se),집계구코드(oa_cd),생활인구합계(tot_lvpop_co),남자0~9세(male_f0t9_lvpop_co),남자10~14세(male_f10t14_lvpop_co),남자15~19세(male_f15t19_lvpop_co),남자20~24세(male_f20t24_lvpop_co),남자25~29세(male_f25t29_lvpop_co),남자30~34세(male_f30t34_lvpop_co),...,여자40~44세(female_f40t44_lvpop_co),여자45~49세(female_f45t49_lvpop_co),여자50~54세(female_f50t54_lvpop_co),여자55~59세(female_f55t59_lvpop_co),여자60~64세(female_f60t64_lvpop_co),여자65~69세(female_f65t69_lvpop_co),여자70~74세(female_f70t74_lvpop_co),여자75~79세(female_f75t79_lvpop_co),여자80세이상(female_above_80_lvpop_co),등록일자(ldadng_dt)
일자(stdr_de_id),,,,,,,,,,,,,,,,,,,,,
20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,13.4910,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,8.4651,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,1.2299,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,27.6958,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,115.6026,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44

In [28]:
sample.index

Index([20170226, 20180107, 20180317, 20190222, 20210706, 20170801, 20190502,
       20170408, 20200614, 20201222,
       ...
       20190817, 20190426, 20170214, 20191123, 20190130, 20170603, 20211007,
       20200819, 20171011, 20200725],
      dtype='int64', name='일자(stdr_de_id)', length=500)

In [29]:
sample = pd.read_csv("./내국인 생활인구.csv", encoding='cp949')
sample.head()

,일자(stdr_de_id),시간(tmzon_pd_se),행정동코드(adstrd_code_se),집계구코드(oa_cd),생활인구합계(tot_lvpop_co),남자0~9세(male_f0t9_lvpop_co),남자10~14세(male_f10t14_lvpop_co),남자15~19세(male_f15t19_lvpop_co),남자20~24세(male_f20t24_lvpop_co),남자25~29세(male_f25t29_lvpop_co),...,여자40~44세(female_f40t44_lvpop_co),여자45~49세(female_f45t49_lvpop_co),여자50~54세(female_f50t54_lvpop_co),여자55~59세(female_f55t59_lvpop_co),여자60~64세(female_f60t64_lvpop_co),여자65~69세(female_f65t69_lvpop_co),여자70~74세(female_f70t74_lvpop_co),여자75~79세(female_f75t79_lvpop_co),여자80세이상(female_above_80_lvpop_co),등록일자(ldadng_dt)
0,20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
1,20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
2,20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
3,20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
4,20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44

In [32]:
sample = sample.set_index("일자(stdr_de_id)")
sample.head()

,시간(tmzon_pd_se),행정동코드(adstrd_code_se),집계구코드(oa_cd),생활인구합계(tot_lvpop_co),남자0~9세(male_f0t9_lvpop_co),남자10~14세(male_f10t14_lvpop_co),남자15~19세(male_f15t19_lvpop_co),남자20~24세(male_f20t24_lvpop_co),남자25~29세(male_f25t29_lvpop_co),남자30~34세(male_f30t34_lvpop_co),...,여자40~44세(female_f40t44_lvpop_co),여자45~49세(female_f45t49_lvpop_co),여자50~54세(female_f50t54_lvpop_co),여자55~59세(female_f55t59_lvpop_co),여자60~64세(female_f60t64_lvpop_co),여자65~69세(female_f65t69_lvpop_co),여자70~74세(female_f70t74_lvpop_co),여자75~79세(female_f75t79_lvpop_co),여자80세이상(female_above_80_lvpop_co),등록일자(ldadng_dt)
일자(stdr_de_id),,,,,,,,,,,,,,,,,,,,,
20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,13.4910,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,8.4651,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,1.2299,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,27.6958,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,115.6026,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44

In [33]:
sample.index

Index([20170226, 20180107, 20180317, 20190222, 20210706, 20170801, 20190502,
       20170408, 20200614, 20201222,
       ...
       20190817, 20190426, 20170214, 20191123, 20190130, 20170603, 20211007,
       20200819, 20171011, 20200725],
      dtype='int64', name='일자(stdr_de_id)', length=500)